spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/flash_booking}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}

reservation:
  expiration-seconds: ${RESERVATION_EXPIRATION_SECONDS:300s}
  expiration-scheduler: ${RESERVATION_EXPIRATION_SCHEDULER_MS:1s}
